on: 
  push:
   branches:
      - '*'
      - '!dev'
name: 🚀 Build, deploy joomla module
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 🔨 Build module
        run: |
          npm install
          npm run build-package
        working-directory: ./modules/mod_socialmedia/build/  
      - name: List output files
        run: find ./modules/mod_socialmedia/build/pkg/ -print

      - name: 📂 Sync module files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.SERVER_NAME }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          local-dir: ./modules/com_profiles/build/package/
          server-dir: ${{ secrets.SERVER_DIR }}